# Generated by Django 4.2.7 on 2024-10-22 19:55

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('phone_number', models.CharField(max_length=16)),
                ('id_registry', models.CharField(max_length=11)),
                ('total_access', models.BooleanField(default=False)),
                ('category', models.IntegerField(choices=[(0, 'Estagiário'), (1, 'Secretário')], default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id_registry_type', models.PositiveSmallIntegerField(choices=[(0, 'CPF'), (1, 'CNPJ')], default=0)),
                ('id_registry', models.CharField(max_length=14)),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('social_name', models.CharField(max_length=100, null=True)),
                ('initials', models.CharField(max_length=20, null=True)),
                ('site_url', models.CharField(blank=True, max_length=120, null=True)),
                ('digital', models.BooleanField(default=False)),
                ('responsible_name', models.CharField(max_length=100, null=True)),
                ('responsible_signature', models.ImageField(blank=True, null=True, upload_to='images')),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='address.address')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
